{"name": "Авторизация пользователя с неверным паролем", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <Diplom.Diplom_2.tests.test_login.TestLogin object at 0x000002690A3746B0>, create_user = ([], <Response [403]>), pwd = 'mnsucahhzv'\n\n    @allure.title('Авторизация пользователя с неверным паролем')\n    @pytest.mark.parametrize('pwd', [gen(10)])\n    def test_login_incorrect_user_password(self, create_user, pwd):\n        login, resp = create_user\n    \n>       email = login[0]\nE       IndexError: list index out of range\n\ntests\\test_login.py:57: IndexError"}, "parameters": [{"name": "pwd", "value": "'mnsucahhzv'"}], "start": 1716134124337, "stop": 1716134124337, "uuid": "e2371e0d-c931-47b6-8fd7-71a91cfbae0b", "historyId": "b965501381f8d0425515f1e078936407", "testCaseId": "f157df1c92204d7519bd37f5dbdd659c", "fullName": "tests.test_login.TestLogin#test_login_incorrect_user_password", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "kekas"}, {"name": "thread", "value": "12848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}